name: Generate XML Sitemap

on:
  push:
    branches:
      - main
    paths:
      - '**/*.html'

permissions:
  contents: write

jobs:
  sitemap:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Fetch all history for git log to accurately determine modification dates

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Generate Sitemap
        run: node generate-sitemap.js

      - name: Commit and Push sitemap.xml if updated
        run: |
          git config --global user.name 'Muhammed Nasih K P'
          git config --global user.email 'nasihkp0271@gmail.com'
          git add sitemap.xml
          git diff --quiet && git diff --staged --quiet || (git commit -m "auto: regenerate sitemap.xml" && git push)
